bridge_ip: 192.168.178.42
location:
  latitude: 52.2059
  longitude: 8.0755
  elevation: 110
scenes:
  'false':
    status: false
    bri: 0
    sat: 0
    ct: 0
    t_time: 10
  night:
    status: true
    bri: 1
    sat: 254
    ct: 447
    t_time: 30
  warm_min:
    status: true
    bri: 80
    sat: 150
    ct: 350
    t_time: 50
  warm_mid:
    status: true
    bri: 170
    sat: 150
    ct: 350
    t_time: 50
  warm_max:
    status: true
    bri: 254
    sat: 150
    ct: 350
    t_time: 10
  cold_max:
    status: true
    bri: 254
    sat: 0
    ct: 250
    t_time: 10
rooms:
- name: Wohnzimmer
  group_ids:
  - 89
  switch_ids:
  - 5
  - 99
  sensor_id: 2
- name: Flur
  group_ids:
  - 83
  switch_ids:
  - 5
  - 99
  sensor_id: 190
- name: Zimmer_Olli
  group_ids:
  - 1
  switch_ids: []
  sensor_id: 2
routines:
- name: Wohnzimmer Routine
  room_name: Wohnzimmer
  daily_time:
    H1: 0
    M1: 0
    H2: 23
    M2: 59
  sections:
    morning:
      time:
        type: sunrise
        offset: -15
      scene_name: warm_min
      bri_check: false
      max_light_level: 0
      x_scene_name: 'off'
    day:
      time:
        type: fixed
        value: 09:00
      scene_name: warm_mid
      bri_check: true
      max_light_level: 18000
      x_scene_name: 'off'
    evening:
      time:
        type: sunset
        offset: 0
      scene_name: warm_max
      bri_check: false
      max_light_level: 0
      x_scene_name: 'off'
    night:
      time:
        type: fixed
        value: '22:30'
      scene_name: night
      bri_check: false
      max_light_level: 0
      x_scene_name: 'off'
- name: Mein zimmer
  room_name: Zimmer_Olli
  sections:
    morning:
      time:
        type: fixed
        value: '12:00'
      scene_name: 'false'
      x_scene_name: 'false'
      bri_check: false
      max_light_level: 18000
    day:
      time:
        type: fixed
        value: '22:00'
      scene_name: night
      x_scene_name: 'false'
      bri_check: false
      max_light_level: 0
