bridge_ip: 192.168.178.42
location:
  latitude: 52.2059
  longitude: 8.0755
  elevation: 110
scenes:
  'false':
    status: false
    bri: 0
    sat: 0
    ct: 0
    t_time: 10
  night:
    status: true
    bri: 1
    sat: 254
    ct: 447
    t_time: 30
  warm_min:
    status: true
    bri: 80
    sat: 150
    ct: 350
    t_time: 50
  warm_mid:
    status: true
    bri: 170
    sat: 150
    ct: 350
    t_time: 50
  warm_max:
    status: true
    bri: 254
    sat: 150
    ct: 350
    t_time: 10
  cold_max:
    status: true
    bri: 254
    sat: 0
    ct: 250
    t_time: 10
rooms:
- name: Wohnzimmer
  group_ids:
  - 89
  switch_ids:
  - 5
  - 99
  sensor_id: 2
- name: Flur
  group_ids:
  - 83
  switch_ids:
  - 5
  - 99
  sensor_id: 190
- name: Zimmer_Olli
  group_ids:
  - 1
  switch_ids: []
  sensor_id: 2
routines: []
