bridge_ip: 192.168.178.42
global_settings:
  datalogger_interval_minutes: 15
  day_start_time: '12:00'
  hysteresis_percent: 25
  log_level: INFO
  night_start_time: '23:00'
location:
  elevation: 110
  latitude: 52.2059
  longitude: 8.0755
rooms:
- group_ids:
  - 89
  name: Wohnzimmer
  sensor_id: 2
  switch_ids:
  - 5
  - 99
- group_ids:
  - 83
  name: Flur
  sensor_id: 190
  switch_ids:
  - 5
  - 99
- group_ids:
  - 1
  name: Zimmer_Olli
  sensor_id: 2
  switch_ids: []
routines:
- daily_time:
    H1: 8
    M1: 0
    H2: 23
    M2: 0
  day:
    scene_name: red
    x_scene_name: cold_max
    bri_check: true
    max_light_level: 20000
    motion_check: true
    wait_time:
      min: 0
      sec: 10
    do_not_disturb: false
  enabled: true
  evening:
    scene_name: grün
    x_scene_name: cold_max
    bri_check: true
    max_light_level: 20000
    motion_check: true
    wait_time:
      min: 0
      sec: 10
    do_not_disturb: false
  morning:
    scene_name: blau
    x_scene_name: cold_max
    bri_check: true
    max_light_level: 20000
    motion_check: true
    wait_time:
      min: 0
      sec: 10
    do_not_disturb: false
  name: TEST
  night:
    scene_name: gelb
    x_scene_name: cold_max
    bri_check: true
    max_light_level: 20000
    motion_check: true
    wait_time:
      min: 0
      sec: 10
    do_not_disturb: false
  room_name: Zimmer_Olli
scenes:
  blau:
    bri: 254
    hue: 43690
    sat: 254
    status: true
    t_time: 10
  cold_max:
    bri: 254
    ct: 153
    sat: 0
    status: true
    t_time: 10
  gelb:
    bri: 254
    hue: 10558
    sat: 254
    status: true
    t_time: 10
  grün:
    bri: 254
    hue: 20935
    sat: 254
    status: true
    t_time: 10
  night:
    bri: 1
    ct: 447
    sat: 254
    status: true
    t_time: 30
  'off':
    bri: 0
    ct: 300
    sat: 0
    status: false
    t_time: 10
  red:
    bri: 254
    hue: 64443
    sat: 254
    status: true
    t_time: 10
  warm_max:
    bri: 254
    ct: 500
    sat: 0
    status: true
    t_time: 10
  warm_mid:
    bri: 170
    ct: 500
    sat: 0
    status: true
    t_time: 10
  warm_min:
    bri: 29
    ct: 221
    sat: 0
    status: true
    t_time: 10
