bridge_ip: 192.168.178.42
global_settings:
  datalogger_interval_minutes: 15
  day_start_time: '12:00'
  hysteresis_percent: 25
  log_level: INFO
  night_start_time: '23:00'
location:
  elevation: 110
  latitude: 52.2059
  longitude: 8.0755
rooms:
- group_ids:
  - 89
  name: Wohnzimmer
  sensor_id: 2
  switch_ids:
  - 5
  - 99
- group_ids:
  - 83
  name: Flur
  sensor_id: 190
  switch_ids:
  - 5
  - 99
- group_ids:
  - 1
  name: Zimmer_Olli
  sensor_id: 2
  switch_ids: []
- group_ids:
  - 87
  name: Zone_Night_Light
  sensor_id: 193
  switch_ids: []
- group_ids:
  - 83
  name: Zone_Auffahrt
  sensor_id: 190
  switch_ids: []
- group_ids:
  - 91
  name: Zone_Garten
  sensor_id: 193
  switch_ids: []
- group_ids:
  - 89
  name: Zone_Olli
  sensor_id: 2
  switch_ids: []
routines:
- daily_time:
    H1: 7
    H2: 23
    M1: 0
    M2: 0
  day:
    bri_check: true
    do_not_disturb: false
    max_light_level: 18000
    motion_check: false
    scene_name: warm_mid
    wait_time:
      min: 5
      sec: 0
    x_scene_name: warm_max
  enabled: true
  evening:
    bri_check: false
    do_not_disturb: false
    max_light_level: 0
    motion_check: false
    scene_name: warm_mid
    wait_time:
      min: 10
      sec: 0
    x_scene_name: 'off'
  morning:
    bri_check: false
    do_not_disturb: false
    max_light_level: 0
    motion_check: false
    scene_name: warm_mid
    wait_time:
      min: 2
      sec: 0
    x_scene_name: 'off'
  name: Im Haus
  night:
    bri_check: false
    do_not_disturb: false
    max_light_level: 0
    motion_check: false
    scene_name: night
    wait_time:
      min: 1
      sec: 0
    x_scene_name: 'off'
  room_name: Zone_Night_Light
- daily_time:
    H1: 6
    H2: 22
    M1: 30
    M2: 30
  day:
    bri_check: true
    do_not_disturb: false
    max_light_level: 12000
    motion_check: false
    scene_name: 'off'
    wait_time:
      min: 5
      sec: 0
    x_scene_name: warm_max
  enabled: true
  evening:
    bri_check: true
    do_not_disturb: false
    max_light_level: 12000
    motion_check: true
    scene_name: warm_max
    wait_time:
      min: 2
      sec: 0
    x_scene_name: warm_max
  morning:
    bri_check: true
    do_not_disturb: false
    max_light_level: 12000
    motion_check: true
    scene_name: warm_mid
    wait_time:
      min: 2
      sec: 0
    x_scene_name: warm_max
  name: Auffahrt
  night:
    bri_check: false
    do_not_disturb: false
    max_light_level: 0
    motion_check: true
    scene_name: 'off'
    wait_time:
      min: 2
      sec: 0
    x_scene_name: warm_mid
  room_name: Zone_Auffahrt
- daily_time:
    H1: 7
    H2: 23
    M1: 0
    M2: 0
  day:
    bri_check: true
    do_not_disturb: false
    max_light_level: 18000
    motion_check: false
    scene_name: 'off'
    wait_time:
      min: 5
      sec: 0
    x_scene_name: warm_max
  enabled: true
  evening:
    bri_check: true
    do_not_disturb: false
    max_light_level: 12000
    motion_check: true
    scene_name: warm_mid
    wait_time:
      min: 2
      sec: 0
    x_scene_name: warm_max
  morning:
    bri_check: true
    do_not_disturb: false
    max_light_level: 12000
    motion_check: true
    scene_name: warm_mid
    wait_time:
      min: 2
      sec: 0
    x_scene_name: warm_max
  name: Terrasse
  night:
    bri_check: false
    do_not_disturb: false
    max_light_level: 0
    motion_check: true
    scene_name: 'off'
    wait_time:
      min: 2
      sec: 0
    x_scene_name: warm_mid
  room_name: Zone_Garten
- daily_time:
    H1: 9
    H2: 21
    M1: 0
    M2: 0
  day:
    bri_check: true
    do_not_disturb: true
    max_light_level: 10000
    motion_check: false
    scene_name: 'off'
    wait_time:
      min: 0
      sec: 0
    x_scene_name: warm_max
  enabled: true
  evening:
    bri_check: false
    do_not_disturb: true
    max_light_level: 0
    motion_check: false
    scene_name: 'off'
    wait_time:
      min: 2
      sec: 0
    x_scene_name: warm_mid
  morning:
    bri_check: false
    do_not_disturb: true
    max_light_level: 0
    motion_check: false
    scene_name: 'off'
    wait_time:
      min: 0
      sec: 0
    x_scene_name: 'off'
  name: Olli
  night:
    bri_check: false
    do_not_disturb: true
    max_light_level: 0
    motion_check: true
    scene_name: 'off'
    wait_time:
      min: 0
      sec: 45
    x_scene_name: night
  room_name: Zone_Olli
scenes:
  blau:
    bri: 254
    hue: 43690
    sat: 254
    status: true
    t_time: 10
  cold_max:
    bri: 254
    ct: 153
    sat: 0
    status: true
    t_time: 10
  gelb:
    bri: 254
    hue: 10558
    sat: 254
    status: true
    t_time: 10
  grün:
    bri: 254
    hue: 20935
    sat: 254
    status: true
    t_time: 10
  night:
    bri: 1
    ct: 447
    sat: 254
    status: true
    t_time: 30
  'off':
    bri: 0
    ct: 300
    sat: 0
    status: false
    t_time: 10
  red:
    bri: 254
    hue: 64443
    sat: 254
    status: true
    t_time: 10
  warm_max:
    bri: 254
    ct: 374
    sat: 0
    status: true
    t_time: 10
  warm_mid:
    bri: 170
    ct: 500
    sat: 0
    status: true
    t_time: 10
  warm_min:
    bri: 29
    ct: 221
    sat: 0
    status: true
    t_time: 10
