[project]
name = "philipshue-day-routine"
version = "0.1.0"
description = "A Philips Hue daily routine controller."
requires-python = ">=3.8"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"